docker:
  image: yegor256/papers
assets:
  id_rsa: "zerocracy/home#assets/blog/id_rsa"
  id_rsa.pub: "zerocracy/home#assets/blog/id_rsa.pub"
merge:
  script: |
    rake
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/g" tex/_version.tex
    sed -i "s/0\.0\.0/${tag}/g" html/index.html
    git add tex/_version.tex html/index.html
    git commit -m "Version set to ${tag}"
    rake
    mkdir -p ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git config --global user.email "rultor@zold.io"
    git config --global user.name "Rultor"
    temp=$(mktemp -d)
    cp target/*.pdf ${temp}
    git checkout gh-pages
    git clean -fd
    cp -R ${temp}/*.pdf .
    git add .
    git commit -am "New papers, version ${tag}"
    git push origin gh-pages

